// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfsamagsczcyattdxyxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhmc2FtYWdzY3pjeWF0dGR4eXh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1Mzg3MzIsImV4cCI6MjA3MDExNDczMn0.hPe6ofrCO6Hb-DfNyxuQH01zLweQgRV37YUF4aHjas8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});